config/routes.rb
Rails.application.routes.draw do
  root 'meal_prep_schedules#index'
  resources :meal_prep_schedules do
    resources :items, controller: 'meal_prep_schedules/items', only: %i(new create edit update destroy)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/meal_prep_schedule.rb
class MealPrepSchedule < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/meal_prep_schedule/creator.rb
class MealPrepSchedule::Creator
  INITIAL_MAIN_COUNT = 4
  INITIAL_SIDE_COUNT = 7

  def create_schedule!(column_params, initial_item_count, base_item_schedule_id = nil)
    meal_prep_schedule = MealPrepSchedule.new(column_params)

    ActiveRecord::Base.transaction do
      meal_prep_schedule.save!

      # 引き継ぎ元のスケジュールから対象のアイテムを複製
      if base_item_schedule_id.present?
        duplicate_prepared_items(base_item_schedule_id, meal_prep_schedule.id)
      end

      # 引き継ぎ対象アイテムのmeal pointから残りの要作成アイテムを計算(小数点切り捨て)
      sum_of_prepared_main_meal_point = meal_prep_schedule.items.main.prepared.map(&:meal_point).sum
      sum_of_created_side_meal_point = meal_prep_schedule.items.side.prepared.map(&:meal_point).sum
      initial_count_params = {
        main: initial_item_count[:main] - sum_of_prepared_main_meal_point.floor,
        side: initial_item_count[:side] - sum_of_created_side_meal_point.floor
      }

      create_initial_item_params(initial_count_params).each do |item_param|
        meal_prep_schedule.items.create!(item_param)
      end
    end

    Result.new(schedule: meal_prep_schedule)
  rescue
    Result.new(succeeded: false)
  end

  private

  def create_initial_item_params(initial_count_params)
    main_count = initial_count_params[:main]
    side_count = initial_count_params[:side]

    main_params = (1..main_count).map { |i| { name: "主菜#{i}", meal_type: :main } }
    side_params = (1..side_count).map { |i| { name: "副菜#{i}", meal_type: :side } }
    main_params + side_params
  end

  def duplicate_prepared_items(base_item_schedule_id, meal_prep_schedule_id)
    base_schedule = MealPrepSchedule.find(base_item_schedule_id)
    base_schedule.items.prepared.map(&:dup).each do |item|
      item.meal_prep_schedule_id = meal_prep_schedule_id
      item.save!
    end
  end

  class Result
    attr_reader :schedule, :succeeded

    def initialize(schedule: nil, succeeded: true)
      @schedule = schedule
      @succeeded = succeeded
    end
  end
end

app/models/meal_prep_schedule/forcaster.rb
class MealPrepSchedule::Forcaster
  MAIN_MEAL_POINT_PER_DATE = 0.6
  SIDE_MEAL_POINT_PER_DATE = 1.3

  def consumption_days_forecast(schedule)
    # NOTE: meal_point = 残量(remaining_rate) ÷ 100
    prepared_meal_point = schedule.items.prepared.sum(:remaining_rate).to_f / 100
    (prepared_meal_point / consumption_meal_point_per_date).floor(1)
  end

  private

  def consumption_meal_point_per_date
    MAIN_MEAL_POINT_PER_DATE + SIDE_MEAL_POINT_PER_DATE
  end
end

app/models/meal_prep_schedule/item.rb
class MealPrepSchedule::Item < ApplicationRecord
  belongs_to :schedule, class_name: 'MealPrepSchedule', foreign_key: "meal_prep_schedule_id"
  validates :name, presence: true
  validate :remaining_rate_can_not_update_in_unprepared_item
  validates :remaining_rate, numericality: {greater_than_or_equal_to: 0,less_than_or_equal_to: 100}

  enum :meal_type, { main: 0, side: 1 }

  scope :prepared, -> { where(prepared: true).where.not(remaining_rate: 0) }
  scope :consumed, -> { where(remaining_rate: 0) }

  def remaining_rate_can_not_update_in_unprepared_item
    if prepared.blank? && remaining_rate != 100
      errors.add(:remaining_rate, 'cannot be update when item is not prepared')
    end
  end

  def meal_point
    remaining_rate.to_f / 100
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_meal_prep_item, only: %i[ show edit update destroy ]

  def index
    schedule = MealPrepSchedule.find(params[:meal_prep_schedule_id])
    @meal_prep_items = schedule.items.all
  end

  def show
  end

  def new
    schedule = MealPrepSchedule.find(params[:meal_prep_schedule_id])
    @meal_prep_item = schedule.items.build
  end

  def edit
  end

  def create
    @meal_prep_item = MealPrepSchedule::Item.new(meal_prep_item_params)

    if @meal_prep_item.save!
      redirect_to meal_prep_schedule_item_url(id: @meal_prep_item.id), notice: "Meal prep item was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @meal_prep_item.update!(meal_prep_item_params)
      redirect_to meal_prep_schedule_items_url(meal_prep_schedule_id: @meal_prep_item.meal_prep_schedule, id: @meal_prep_item), notice: "Meal prep item was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @meal_prep_item.destroy!

    redirect_to meal_prep_schedule_items_url, notice: "Meal prep item was successfully destroyed."
  end

  private

  def set_meal_prep_item
    schedule = MealPrepSchedule.find(params[:meal_prep_schedule_id])
    @meal_prep_item = schedule.items.find(params[:id])
  end

  def meal_prep_item_params
    params.require(:meal_prep_schedule_item).permit(:name, :prepared, :meal_type, :meal_prep_schedule_id)
  end
end

app/controllers/meal_prep_schedules/items_controller.rb
class MealPrepSchedules::ItemsController < ApplicationController
  def new
    schedule = MealPrepSchedule.find(params[:meal_prep_schedule_id])
    @meal_prep_item = schedule.items.build
  end

  def edit
    @meal_prep_item = load_meal_prep_item
  end

  def create
    @meal_prep_item = MealPrepSchedule::Item.new(meal_prep_item_params)

    if @meal_prep_item.save!
      redirect_to meal_prep_schedule_path(id: @meal_prep_item.schedule), notice: 'Meal prep item was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @meal_prep_item = load_meal_prep_item

    if @meal_prep_item.update(meal_prep_item_params)
      redirect_to meal_prep_schedule_path(id: @meal_prep_item.schedule), notice: 'Meal prep item was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @meal_prep_item = load_meal_prep_item
    @meal_prep_item.destroy!

    redirect_to meal_prep_schedule_path(@meal_prep_item.schedule), notice: 'Meal prep item was successfully destroyed.'
  end

  private

  def load_meal_prep_item
    schedule = MealPrepSchedule.find(params[:meal_prep_schedule_id])
    schedule.items.find(params[:id])
  end

  def meal_prep_item_params
    params.require(:meal_prep_schedule_item).permit(:name, :prepared, :meal_type, :remaining_rate, :meal_prep_schedule_id)
  end
end

app/controllers/meal_prep_schedules_controller.rb
class MealPrepSchedulesController < ApplicationController
  before_action :set_meal_prep_schedule, only: %i[ show edit update destroy ]

  def index
    @meal_prep_schedules = MealPrepSchedule.all
  end

  def show
  end

  def new
    @meal_prep_schedule = MealPrepSchedule.new
  end

  def edit
  end

  def create
    params = meal_prep_schedule_params
    column_params = params.slice(:name, :memo)
    base_item_schedule_id = params[:base_item_schedule_id]
    initial_item_count = { main: params[:main_count].to_i, side: params[:side_count].to_i }

    result = MealPrepSchedule::Creator.new.create_schedule!(column_params, initial_item_count, base_item_schedule_id)

    @meal_prep_schedule = result.schedule

    if @meal_prep_schedule.present?
      redirect_to meal_prep_schedule_url(@meal_prep_schedule), notice: "Meal prep schedule was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @meal_prep_schedule.update(meal_prep_schedule_params)
      redirect_to meal_prep_schedule_url(@meal_prep_schedule), notice: "Meal prep schedule was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @meal_prep_schedule.destroy

    redirect_to meal_prep_schedules_url, notice: "Meal prep schedule was successfully destroyed."
  end

  private

  def set_meal_prep_schedule
    @meal_prep_schedule = MealPrepSchedule.find(params[:id])
  end

  def meal_prep_schedule_params
    params.require(:meal_prep_schedule).permit(:name, :memo, :main_count, :side_count, :base_item_schedule_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MealPrep</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/meal_prep_schedules/_form.html.erb
<%= form_with(model: meal_prep_schedule) do |form| %>
  <% if meal_prep_schedule.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(meal_prep_schedule.errors.count, "error") %> prohibited this meal_prep_schedule from being saved:</h2>

      <ul>
        <% meal_prep_schedule.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <% unless meal_prep_schedule.persisted? %>
    <div>
      <%= form.label :main_count, style: "display: block" %>
      <%= form.text_field :main_count, value: MealPrepSchedule::Creator::INITIAL_MAIN_COUNT %>
    </div>
  
    <div>
      <%= form.label :side_count, style: "display: block" %>
      <%= form.text_field :side_count, value: MealPrepSchedule::Creator::INITIAL_SIDE_COUNT %>
    </div>

    <div>
      <%= form.label :base_item_schedule_id, style: "display: block" %>
      <%= form.text_field :base_item_schedule_id %>
    </div>
  <% end %>

  <div>
    <%= form.label :memo, style: "display: block" %>
    <%= form.text_area :memo %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/meal_prep_schedules/_item_list.erb
<h2>Item List</h2>
<h4>準備済み</h4>
<section>
  <% items.prepared.each do |item| %>
    <div>
      <%= item.meal_type %>
      <%= link_to item.name, edit_meal_prep_schedule_item_path(meal_prep_schedule_id: @meal_prep_schedule, id: item) %>
      <%= "残量(%): #{item.remaining_rate}%" %>
    </div>
  <% end %>
</section>

<h4>準備待ち</h4>
<section>
  <% items.where(prepared: false).each do |item| %>
    <div>
      <%= link_to item.name, edit_meal_prep_schedule_item_path(meal_prep_schedule_id: @meal_prep_schedule, id: item) %>
    </div>
  <% end %>
</section>

<h4>消化済み</h4>
<section>
  <% items.consumed.each do |item| %>
    <div>
      <%= link_to item.name, edit_meal_prep_schedule_item_path(meal_prep_schedule_id: @meal_prep_schedule, id: item) %>
    </div>
  <% end %>
</section>

app/views/meal_prep_schedules/_meal_prep_schedule.html.erb
<div id="<%= dom_id meal_prep_schedule %>">
  <p>
    <strong>Name:</strong>
    <%= meal_prep_schedule.name %>
  </p>

</div>

app/views/meal_prep_schedules/edit.html.erb
<h1>Editing meal prep schedule</h1>

<%= render "form", meal_prep_schedule: @meal_prep_schedule %>

<br>

<div>
  <%= link_to "Show this meal prep schedule", @meal_prep_schedule %> |
  <%= link_to "Back to meal prep schedules", meal_prep_schedules_path %>
</div>

app/views/meal_prep_schedules/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Meal prep schedules</h1>

<div id="meal_prep_schedules">
  <% @meal_prep_schedules.each do |meal_prep_schedule| %>
    <%= render meal_prep_schedule %>
    <p>
      <%= link_to "Show this meal prep schedule", meal_prep_schedule %>
    </p>
  <% end %>
</div>

<%= link_to "New meal prep schedule", new_meal_prep_schedule_path %>

app/views/meal_prep_schedules/items/_form.html.erb
<%= form_with(model: meal_prep_item, url: url) do |form| %>
  <% if meal_prep_item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(meal_prep_item.errors.count, "error") %> prohibited this meal_prep_item from being saved:</h2>

      <ul>
        <% meal_prep_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :prepared, style: "display: block" %>
    <%= form.check_box :prepared %>
  </div>

  <div>
    <%= form.radio_button :meal_type, 'main' %>
    <%= form.label :meal_type_main, '主菜' %>
    <%= form.radio_button :meal_type, 'side' %>
    <%= form.label :age_adult, '副菜' %>
  </div>

  <div>
    <%= form.label :remaining_rate, '残量(%)' %>
    <%= form.number_field :remaining_rate %>
  </div>

  <div>
    <%= form.label :meal_prep_schedule_id %>
    <%= form.number_field :meal_prep_schedule_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/meal_prep_schedules/items/_meal_prep_item.html.erb
<div id="<%= dom_id meal_prep_item %>">
  <p>
    <strong>Name:</strong>
    <%= meal_prep_item.name %>
  </p>

  <p>
    <strong>Prepared:</strong>
    <%= meal_prep_item.prepared %>
  </p>

  <p>
    <strong>Meal type:</strong>
    <%= meal_prep_item.meal_type %>
  </p>

</div>

app/views/meal_prep_schedules/items/edit.html.erb
<h1>Editing meal prep item</h1>

<%= render "form", meal_prep_item: @meal_prep_item, url: meal_prep_schedule_item_url(meal_prep_schedule_id: @meal_prep_item.schedule, id: @meal_prep_item) %>
<%= 
  button_to "Destroy this meal prep item",
  meal_prep_schedule_item_path(meal_prep_schedule_id: @meal_prep_item.schedule, id: @meal_prep_item), 
  method: :delete, 
  form: { data: { turbo_confirm: "削除しますか？" } } 
%>
<br>

<div>
  <%= link_to "Back to schedule", meal_prep_schedule_path(id: @meal_prep_item.schedule) %>
</div>

app/views/meal_prep_schedules/items/new.html.erb
<h1>New meal prep item</h1>

<%= render "form", meal_prep_item: @meal_prep_item, url: meal_prep_schedule_items_path(meal_prep_schedule_id: @meal_prep_item.schedule) %>

<br>

<div>
  <%= link_to "Back to schedule", meal_prep_schedule_path(id: @meal_prep_item.schedule) %>
</div>

app/views/meal_prep_schedules/new.html.erb
<h1>New meal prep schedule</h1>

<%= render "form", meal_prep_schedule: @meal_prep_schedule %>

<br>

<div>
  <%= link_to "Back to meal prep schedules", meal_prep_schedules_path %>
</div>

app/views/meal_prep_schedules/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @meal_prep_schedule %>

<section>
  <h2>Schedule Status</h2>
  <%= @meal_prep_schedule.schedule_status %>
  <%= "作り置き消化予測日数: #{MealPrepSchedule::Forcaster.new.consumption_days_forecast(@meal_prep_schedule)}日" %>
</section>

<%= render 'item_list', items: @meal_prep_schedule.items %>
<section>
  <h2>Memo</h2>
  <%= @meal_prep_schedule.memo %>
</section>

<%= link_to "New meal prep item", new_meal_prep_schedule_item_path(meal_prep_schedule_id: @meal_prep_schedule) %>

<div>
  <%= link_to "Edit this meal prep schedule", edit_meal_prep_schedule_path(@meal_prep_schedule) %> |
  <%= link_to "Back to meal prep schedules", meal_prep_schedules_path %>

  <%= button_to "Destroy this meal prep schedule", @meal_prep_schedule, method: :delete, form: { data: { turbo_confirm: "削除しますか？" } } %>
</div>